import type { GoogleReview, GoogleReviewsSnapshot } from "./types";

// Google reviews URL (opens Albarakahoney reviews on Google)
export const GOOGLE_REVIEWS_URL =
  "https://www.google.com/search?q=Albarakahoney&stick=H4sIAAAAAAAA_-NgU1I1qLAwTTO2MDQ2tzA1NDAyMzO3MqgwM09OMUtNM041SEoyM05KXcTK65iTlFiUmJ2YkZ-XWgkAsxoljDkAAAA&hl=en&mat=CczGenslMjjRElcBa0lj_-KXNyOjmf8lrRhzZCkpnMb_db4-odPRRGPwCJ-sKx8A5eaXgAm0DYYpkDaW7CODOa3gD_1E4f8DAcNZgouVFYPZlMJiRjTBXhul3lLBhSjHuvI#mpd=~15075854889189557964/customers/reviews&lrd=0x85f3813785102667:0x67cd6ef3e0bb63be,1,,,,";

export const getGoogleReviewPageUrl = (review: GoogleReview) =>
  review.googleMapsUri || GOOGLE_REVIEWS_URL;

// Google write review URL
export const GOOGLE_WRITE_REVIEW_URL =
  "https://search.google.com/local/writereview?placeid=ChIJZyYQhTeB84URvmO74PNuzWc";

// Manually curated Google reviews (latest first)
export const GOOGLE_REVIEWS: GoogleReview[] = [
  {
    id: "review-saad-ch-1",
    authorName: "Saad Ch",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "Amazing quality and a very professional website. 🍯✨ The honey looks pure, natural, and premium. Keep up the great work! Highly recommended.",
    relativePublishTimeDescription: "12 hours ago",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-muhammad-ahmad-2",
    authorName: "Muhammad Ahmad",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "Highly recommended",
    relativePublishTimeDescription: "20 hours ago",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-saniyal-aamir-3",
    authorName: "Saniyal Aamir",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "Absolutely loved the honey! 🍯 It tastes fresh, pure, and natural, with a really nice texture and rich flavor. The full review text available in the source was truncated, so the remainder is not included.",
    relativePublishTimeDescription: "24 hours ago",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-saqib-rana-commando-4",
    authorName: "SaQib RaNa (CoMManDo)",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "100 prsnt purr and very very tasty",
    relativePublishTimeDescription: "24 hours ago",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-uzair-hafeez-5",
    authorName: "Uzair Hafeez",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "Really impressed with Al Baraka Honey. The taste is rich, fresh, and naturally sweet, and the quality feels excellent. Great packaging and overall experience. Highly recommended! 🍯",
    relativePublishTimeDescription: "Yesterday",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-rizwan-nazir-6",
    authorName: "rizwan nazir",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "Amazing quality and excellent taste! 🍯 The honey was absolutely delicious, fresh, and pure. You can really taste the natural quality. Highly recommended for anyone looking for good-quality honey. I'll definitely order again! ❤️",
    relativePublishTimeDescription: "Yesterday",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-shoaib-ali-7",
    authorName: "shoaib ali",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "",
    relativePublishTimeDescription: "Yesterday",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-usama-mughal-8",
    authorName: "Usama Mughal",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "A premium-quality honey with a rich, authentic taste and smooth natural texture. The freshness and purity are truly impressive, making it a refined choice for everyday use. The presentation and packaging are equally commendable.",
    relativePublishTimeDescription: "Yesterday",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-rana-sajid-ali-9",
    authorName: "Rana Sajid Ali",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "I found Best quality honey here.... Such an amazing product.... U people must try it .... Highly satisfied and recommended....",
    relativePublishTimeDescription: "Yesterday",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-vicky-baba-10",
    authorName: "Vicky Baba",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "I have recently ordered from Al-Baraka Honey. It is very fresh and delicious. It is available in a much fresher and higher packaging than the market. Their rate is also reasonable according to the market rate. So I would recommend that everyone should buy it. You will get a good deal from Al-Baraka Honey.",
    relativePublishTimeDescription: "2 days ago",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-hassan-raza-11",
    authorName: "Hassan Raza",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "Great honey! The packaging is clean nice and premium, the taste is delicious and authentic, and the quality is top-notch. I'm very satisfied with this purchase and would definitely recommend it to others.",
    relativePublishTimeDescription: "2 days ago",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-shahzad-yaqub-12",
    authorName: "shahzad yaqub",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "Small bees make such delicious, natural honey! 🍯 The taste is pure, fresh, and naturally sweet—I really enjoyed it. Highly recommended.",
    relativePublishTimeDescription: "2 days ago",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-tajammal-hussain-13",
    authorName: "Tajammal Hussain",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "Very good , excellent, fabolous ..",
    relativePublishTimeDescription: "2 days ago",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-homind-hidden-chapters-14",
    authorName: "Homind hidden chapters",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "بہت اچھا اور خالص ذائقہ، کوالٹی بھی بہترین ہے۔ دوبارہ ضرور خریدوں گا۔",
    relativePublishTimeDescription: "2 days ago",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-aizaz-lala-15",
    authorName: "aizaz lala",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "100% recommended",
    relativePublishTimeDescription: "2 days ago",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-haji-muhammad-yasir-rehman-16",
    authorName: "Haji Muhammad Yasir Rehman",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "I've just tried this honey and I'm genuinely impressed. I'll definitely be buying it again and would highly recommend it to anyone who loves natural honey. 🍯❤️🙋‍♂️",
    relativePublishTimeDescription: "2 days ago",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-mariam-shahid-17",
    authorName: "Mariam Shahid",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "Bohat awla, bht natural, no mixing. Loved every bit of it. Will definitely order more",
    relativePublishTimeDescription: "2 days ago",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-atir-ali0321-18",
    authorName: "atir ali0321",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "",
    relativePublishTimeDescription: "2 weeks ago",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-waqas-bhatti-19",
    authorName: "Waqas Bhatti",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "Absolutely love this honey! The packaging looks elegant, the flavor is rich and authentic, and the quality is excellent. Really happy with my purchase and would definitely recommend it!",
    relativePublishTimeDescription: "3 weeks ago",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-musawer-ali-20",
    authorName: "Musawer Ali",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "I really loved the honey. It's 100% natural and healthy.",
    relativePublishTimeDescription: "4 weeks ago",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-imranali-ali-21",
    authorName: "Imranali Ali",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "I highly recommend Al Baraka Honey. I will definitely order again. Everything is amazing paking. Delivery and quality.",
    relativePublishTimeDescription: "4 weeks ago",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-syed-javed-ali-22",
    authorName: "syed javed ali",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "excellent good quality",
    relativePublishTimeDescription: "4 weeks ago",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-zainab-fatima-23",
    authorName: "Zainab Fatima",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "Quality of the honey is very good. Specially the pricing is very reasonable. Worth buying. Will surely purchase it again.",
    relativePublishTimeDescription: "4 weeks ago",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-umer-farooq-24",
    authorName: "Umer Farooq",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "Absolutely love this honey! 🍯 You can immediately tell it's 100% natural and pure. The taste is [full text not available in the supplied source].",
    relativePublishTimeDescription: "4 weeks ago",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-nafees-ul-hassan-jafari-25",
    authorName: "Nafees Ul Hassan Jafari",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "I recently purchased honey from Al Baraka Honey, and I am genuinely impressed with the quality. The honey tastes pure, fresh, and completely natural. You can easily tell it is authentic and not overly processed like many products available in the market.\n\nThe packaging was excellent, delivery was on time, and the overall experience was smooth. If you're looking for high-quality, genuine honey, I highly recommend Al Baraka Honey. I will definitely order again.",
    relativePublishTimeDescription: "4 weeks ago",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-afzal-khan-26",
    authorName: "Afzal Khan",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "Okay so I usually don't post reviews, but Al-Baraka Honey actually deserves the hype. I've been trying to eat cleaner lately and swapped out refined sugar for this, and the difference is night and day. It doesn't have that fake, hyper-processed artificial sweet taste—you can tell it's 100% pure raw honey right off the batch. I've been taking a spoonful in warm water every morning, and honestly my energy levels and digestion have been so much better. It's lowkey become an essential part of my daily routine now. If you're looking for authentic honey that actually delivers on health benefits, don't sleep on this. 10/10 elite quality! 🍯🔥",
    relativePublishTimeDescription: "4 weeks ago",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-sohail-bajwa-27",
    authorName: "Sohail Bajwa",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "بہت اعلٰی معیار کا انتہائی سستا شہد ھے اللہ پاک کاروبار میں مزید برکت عطا کرے آمین ثم آمین ❤️ نائس ❣️",
    relativePublishTimeDescription: "5 weeks ago",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-usama-bin-abdul-28",
    authorName: "Usama Bin Abdul",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "Absolutely pure, rich in natural taste, and one of the best honey products I've ever tried—highly recommended!",
    relativePublishTimeDescription: "6 weeks ago",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-adil-r-29",
    authorName: "Adil R",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "Excellent honey! The packaging is clean and premium, the taste is delicious and authentic, and the quality is top-notch. I'm very satisfied with this purchase and would definitely recommend it to others.",
    relativePublishTimeDescription: "6 weeks ago",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
  {
    id: "review-wordpress-doctor-30",
    authorName: "Wordpress Doctor",
    authorUri: "",
    authorPhotoUri: null,
    rating: 5,
    text: "Excellent Quality Honey!... [full text not available in the supplied source]",
    relativePublishTimeDescription: "6 weeks ago",
    publishTime: "",
    googleMapsUri: GOOGLE_REVIEWS_URL,
    flagContentUri: null,
  },
];

export const GOOGLE_REVIEWS_SNAPSHOT: GoogleReviewsSnapshot = {
  placeName: "Albarakahoney",
  rating: 5,
  totalReviews: 30,
  googleMapsUri: GOOGLE_REVIEWS_URL,
  reviews: GOOGLE_REVIEWS,
};
